// AUTO-GENERATED by scripts/generate-art-map.mjs — do not edit by hand.
import type { ImageSourcePropType } from "react-native";
import drinkLanxiongDense from "../assets/store-art/drink-lanxiong-dense.webp";
import drinkLanxiongSparse from "../assets/store-art/drink-lanxiong-sparse.webp";
import drinkLanxiongGlow from "../assets/store-art/drink-lanxiong-glow.webp";
import drinkChabaidaoDense from "../assets/store-art/drink-chabaidao-dense.webp";
import drinkChabaidaoSparse from "../assets/store-art/drink-chabaidao-sparse.webp";
import drinkChabaidaoGlow from "../assets/store-art/drink-chabaidao-glow.webp";
import drinkChaosYogurtDense from "../assets/store-art/drink-chaos-yogurt-dense.webp";
import drinkChaosYogurtSparse from "../assets/store-art/drink-chaos-yogurt-sparse.webp";
import drinkChaosYogurtGlow from "../assets/store-art/drink-chaos-yogurt-glow.webp";
import drinkYeyeDense from "../assets/store-art/drink-yeye-dense.webp";
import drinkYeyeSparse from "../assets/store-art/drink-yeye-sparse.webp";
import drinkYeyeGlow from "../assets/store-art/drink-yeye-glow.webp";
import drinkLuckinDense from "../assets/store-art/drink-luckin-dense.webp";
import drinkLuckinSparse from "../assets/store-art/drink-luckin-sparse.webp";
import drinkLuckinGlow from "../assets/store-art/drink-luckin-glow.webp";
import drinkQintiantianDense from "../assets/store-art/drink-qintiantian-dense.webp";
import drinkQintiantianSparse from "../assets/store-art/drink-qintiantian-sparse.webp";
import drinkQintiantianGlow from "../assets/store-art/drink-qintiantian-glow.webp";
import drinkCocoDense from "../assets/store-art/drink-coco-dense.webp";
import drinkCocoSparse from "../assets/store-art/drink-coco-sparse.webp";
import drinkCocoGlow from "../assets/store-art/drink-coco-glow.webp";
import drinkMoreYogurtDense from "../assets/store-art/drink-more-yogurt-dense.webp";
import drinkMoreYogurtSparse from "../assets/store-art/drink-more-yogurt-sparse.webp";
import drinkMoreYogurtGlow from "../assets/store-art/drink-more-yogurt-glow.webp";
import drinkStarbucksDense from "../assets/store-art/drink-starbucks-dense.webp";
import drinkStarbucksSparse from "../assets/store-art/drink-starbucks-sparse.webp";
import drinkStarbucksGlow from "../assets/store-art/drink-starbucks-glow.webp";
import drinkChageeDense from "../assets/store-art/drink-chagee-dense.webp";
import drinkChageeSparse from "../assets/store-art/drink-chagee-sparse.webp";
import drinkChageeGlow from "../assets/store-art/drink-chagee-glow.webp";
import drinkGelatoDense from "../assets/store-art/drink-gelato-dense.webp";
import drinkGelatoSparse from "../assets/store-art/drink-gelato-sparse.webp";
import drinkGelatoGlow from "../assets/store-art/drink-gelato-glow.webp";
import drinkBojooDense from "../assets/store-art/drink-bojoo-dense.webp";
import drinkBojooSparse from "../assets/store-art/drink-bojoo-sparse.webp";
import drinkBojooGlow from "../assets/store-art/drink-bojoo-glow.webp";
import drinkLinleeDense from "../assets/store-art/drink-linlee-dense.webp";
import drinkLinleeSparse from "../assets/store-art/drink-linlee-sparse.webp";
import drinkLinleeGlow from "../assets/store-art/drink-linlee-glow.webp";
import drinkTeasureDense from "../assets/store-art/drink-teasure-dense.webp";
import drinkTeasureSparse from "../assets/store-art/drink-teasure-sparse.webp";
import drinkTeasureGlow from "../assets/store-art/drink-teasure-glow.webp";
import drinkMannerDense from "../assets/store-art/drink-manner-dense.webp";
import drinkMannerSparse from "../assets/store-art/drink-manner-sparse.webp";
import drinkMannerGlow from "../assets/store-art/drink-manner-glow.webp";
import foodZuimianDense from "../assets/store-art/food-zuimian-dense.webp";
import foodZuimianSparse from "../assets/store-art/food-zuimian-sparse.webp";
import foodZuimianGlow from "../assets/store-art/food-zuimian-glow.webp";
import foodLiumianDense from "../assets/store-art/food-liumian-dense.webp";
import foodLiumianSparse from "../assets/store-art/food-liumian-sparse.webp";
import foodLiumianGlow from "../assets/store-art/food-liumian-glow.webp";
import foodLutaiDense from "../assets/store-art/food-lutai-dense.webp";
import foodLutaiSparse from "../assets/store-art/food-lutai-sparse.webp";
import foodLutaiGlow from "../assets/store-art/food-lutai-glow.webp";
import foodZiguluDense from "../assets/store-art/food-zigulu-dense.webp";
import foodZiguluSparse from "../assets/store-art/food-zigulu-sparse.webp";
import foodZiguluGlow from "../assets/store-art/food-zigulu-glow.webp";
import foodZhangruhuoDense from "../assets/store-art/food-zhangruhuo-dense.webp";
import foodZhangruhuoSparse from "../assets/store-art/food-zhangruhuo-sparse.webp";
import foodZhangruhuoGlow from "../assets/store-art/food-zhangruhuo-glow.webp";
import foodMcdonaldsDense from "../assets/store-art/food-mcdonalds-dense.webp";
import foodMcdonaldsSparse from "../assets/store-art/food-mcdonalds-sparse.webp";
import foodMcdonaldsGlow from "../assets/store-art/food-mcdonalds-glow.webp";
import foodJiayibingDense from "../assets/store-art/food-jiayibing-dense.webp";
import foodJiayibingSparse from "../assets/store-art/food-jiayibing-sparse.webp";
import foodJiayibingGlow from "../assets/store-art/food-jiayibing-glow.webp";
import foodMiaoameiDense from "../assets/store-art/food-miaoamei-dense.webp";
import foodMiaoameiSparse from "../assets/store-art/food-miaoamei-sparse.webp";
import foodMiaoameiGlow from "../assets/store-art/food-miaoamei-glow.webp";
import foodZhaoerDense from "../assets/store-art/food-zhaoer-dense.webp";
import foodZhaoerSparse from "../assets/store-art/food-zhaoer-sparse.webp";
import foodZhaoerGlow from "../assets/store-art/food-zhaoer-glow.webp";
import foodBailuyuanDense from "../assets/store-art/food-bailuyuan-dense.webp";
import foodBailuyuanSparse from "../assets/store-art/food-bailuyuan-sparse.webp";
import foodBailuyuanGlow from "../assets/store-art/food-bailuyuan-glow.webp";
import foodLaoxiangjiDense from "../assets/store-art/food-laoxiangji-dense.webp";
import foodLaoxiangjiSparse from "../assets/store-art/food-laoxiangji-sparse.webp";
import foodLaoxiangjiGlow from "../assets/store-art/food-laoxiangji-glow.webp";
import foodJiangzhouziDense from "../assets/store-art/food-jiangzhouzi-dense.webp";
import foodJiangzhouziSparse from "../assets/store-art/food-jiangzhouzi-sparse.webp";
import foodJiangzhouziGlow from "../assets/store-art/food-jiangzhouzi-glow.webp";
import foodHefuDense from "../assets/store-art/food-hefu-dense.webp";
import foodHefuSparse from "../assets/store-art/food-hefu-sparse.webp";
import foodHefuGlow from "../assets/store-art/food-hefu-glow.webp";
import foodShaguopoDense from "../assets/store-art/food-shaguopo-dense.webp";
import foodShaguopoSparse from "../assets/store-art/food-shaguopo-sparse.webp";
import foodShaguopoGlow from "../assets/store-art/food-shaguopo-glow.webp";
import foodMicunDense from "../assets/store-art/food-micun-dense.webp";
import foodMicunSparse from "../assets/store-art/food-micun-sparse.webp";
import foodMicunGlow from "../assets/store-art/food-micun-glow.webp";
import foodJiagelaoDense from "../assets/store-art/food-jiagelao-dense.webp";
import foodJiagelaoSparse from "../assets/store-art/food-jiagelao-sparse.webp";
import foodJiagelaoGlow from "../assets/store-art/food-jiagelao-glow.webp";
import foodTubestationDense from "../assets/store-art/food-tubestation-dense.webp";
import foodTubestationSparse from "../assets/store-art/food-tubestation-sparse.webp";
import foodTubestationGlow from "../assets/store-art/food-tubestation-glow.webp";
import foodXiangshantingDense from "../assets/store-art/food-xiangshanting-dense.webp";
import foodXiangshantingSparse from "../assets/store-art/food-xiangshanting-sparse.webp";
import foodXiangshantingGlow from "../assets/store-art/food-xiangshanting-glow.webp";
import foodXintangDense from "../assets/store-art/food-xintang-dense.webp";
import foodXintangSparse from "../assets/store-art/food-xintang-sparse.webp";
import foodXintangGlow from "../assets/store-art/food-xintang-glow.webp";
import foodYunhaiyaoDense from "../assets/store-art/food-yunhaiyao-dense.webp";
import foodYunhaiyaoSparse from "../assets/store-art/food-yunhaiyao-sparse.webp";
import foodYunhaiyaoGlow from "../assets/store-art/food-yunhaiyao-glow.webp";
import foodSamgyetangDense from "../assets/store-art/food-samgyetang-dense.webp";
import foodSamgyetangSparse from "../assets/store-art/food-samgyetang-sparse.webp";
import foodSamgyetangGlow from "../assets/store-art/food-samgyetang-glow.webp";
import foodXibeiDense from "../assets/store-art/food-xibei-dense.webp";
import foodXibeiSparse from "../assets/store-art/food-xibei-sparse.webp";
import foodXibeiGlow from "../assets/store-art/food-xibei-glow.webp";

export const storeIds = [
  "drink-lanxiong",
  "drink-chabaidao",
  "drink-chaos-yogurt",
  "drink-yeye",
  "drink-luckin",
  "drink-qintiantian",
  "drink-coco",
  "drink-more-yogurt",
  "drink-starbucks",
  "drink-chagee",
  "drink-gelato",
  "drink-bojoo",
  "drink-linlee",
  "drink-teasure",
  "drink-manner",
  "food-zuimian",
  "food-liumian",
  "food-lutai",
  "food-zigulu",
  "food-zhangruhuo",
  "food-mcdonalds",
  "food-jiayibing",
  "food-miaoamei",
  "food-zhaoer",
  "food-bailuyuan",
  "food-laoxiangji",
  "food-jiangzhouzi",
  "food-hefu",
  "food-shaguopo",
  "food-micun",
  "food-jiagelao",
  "food-tubestation",
  "food-xiangshanting",
  "food-xintang",
  "food-yunhaiyao",
  "food-samgyetang",
  "food-xibei"
] as const;

export type StoreId = (typeof storeIds)[number];

export type StoreArtLayers = {
  dense: ImageSourcePropType;
  sparse: ImageSourcePropType;
  glow: ImageSourcePropType;
};

const availableStoreArt = {
  "drink-lanxiong": {
    dense: drinkLanxiongDense,
    sparse: drinkLanxiongSparse,
    glow: drinkLanxiongGlow
  },
  "drink-chabaidao": {
    dense: drinkChabaidaoDense,
    sparse: drinkChabaidaoSparse,
    glow: drinkChabaidaoGlow
  },
  "drink-chaos-yogurt": {
    dense: drinkChaosYogurtDense,
    sparse: drinkChaosYogurtSparse,
    glow: drinkChaosYogurtGlow
  },
  "drink-yeye": {
    dense: drinkYeyeDense,
    sparse: drinkYeyeSparse,
    glow: drinkYeyeGlow
  },
  "drink-luckin": {
    dense: drinkLuckinDense,
    sparse: drinkLuckinSparse,
    glow: drinkLuckinGlow
  },
  "drink-qintiantian": {
    dense: drinkQintiantianDense,
    sparse: drinkQintiantianSparse,
    glow: drinkQintiantianGlow
  },
  "drink-coco": {
    dense: drinkCocoDense,
    sparse: drinkCocoSparse,
    glow: drinkCocoGlow
  },
  "drink-more-yogurt": {
    dense: drinkMoreYogurtDense,
    sparse: drinkMoreYogurtSparse,
    glow: drinkMoreYogurtGlow
  },
  "drink-starbucks": {
    dense: drinkStarbucksDense,
    sparse: drinkStarbucksSparse,
    glow: drinkStarbucksGlow
  },
  "drink-chagee": {
    dense: drinkChageeDense,
    sparse: drinkChageeSparse,
    glow: drinkChageeGlow
  },
  "drink-gelato": {
    dense: drinkGelatoDense,
    sparse: drinkGelatoSparse,
    glow: drinkGelatoGlow
  },
  "drink-bojoo": {
    dense: drinkBojooDense,
    sparse: drinkBojooSparse,
    glow: drinkBojooGlow
  },
  "drink-linlee": {
    dense: drinkLinleeDense,
    sparse: drinkLinleeSparse,
    glow: drinkLinleeGlow
  },
  "drink-teasure": {
    dense: drinkTeasureDense,
    sparse: drinkTeasureSparse,
    glow: drinkTeasureGlow
  },
  "drink-manner": {
    dense: drinkMannerDense,
    sparse: drinkMannerSparse,
    glow: drinkMannerGlow
  },
  "food-zuimian": {
    dense: foodZuimianDense,
    sparse: foodZuimianSparse,
    glow: foodZuimianGlow
  },
  "food-liumian": {
    dense: foodLiumianDense,
    sparse: foodLiumianSparse,
    glow: foodLiumianGlow
  },
  "food-lutai": {
    dense: foodLutaiDense,
    sparse: foodLutaiSparse,
    glow: foodLutaiGlow
  },
  "food-zigulu": {
    dense: foodZiguluDense,
    sparse: foodZiguluSparse,
    glow: foodZiguluGlow
  },
  "food-zhangruhuo": {
    dense: foodZhangruhuoDense,
    sparse: foodZhangruhuoSparse,
    glow: foodZhangruhuoGlow
  },
  "food-mcdonalds": {
    dense: foodMcdonaldsDense,
    sparse: foodMcdonaldsSparse,
    glow: foodMcdonaldsGlow
  },
  "food-jiayibing": {
    dense: foodJiayibingDense,
    sparse: foodJiayibingSparse,
    glow: foodJiayibingGlow
  },
  "food-miaoamei": {
    dense: foodMiaoameiDense,
    sparse: foodMiaoameiSparse,
    glow: foodMiaoameiGlow
  },
  "food-zhaoer": {
    dense: foodZhaoerDense,
    sparse: foodZhaoerSparse,
    glow: foodZhaoerGlow
  },
  "food-bailuyuan": {
    dense: foodBailuyuanDense,
    sparse: foodBailuyuanSparse,
    glow: foodBailuyuanGlow
  },
  "food-laoxiangji": {
    dense: foodLaoxiangjiDense,
    sparse: foodLaoxiangjiSparse,
    glow: foodLaoxiangjiGlow
  },
  "food-jiangzhouzi": {
    dense: foodJiangzhouziDense,
    sparse: foodJiangzhouziSparse,
    glow: foodJiangzhouziGlow
  },
  "food-hefu": {
    dense: foodHefuDense,
    sparse: foodHefuSparse,
    glow: foodHefuGlow
  },
  "food-shaguopo": {
    dense: foodShaguopoDense,
    sparse: foodShaguopoSparse,
    glow: foodShaguopoGlow
  },
  "food-micun": {
    dense: foodMicunDense,
    sparse: foodMicunSparse,
    glow: foodMicunGlow
  },
  "food-jiagelao": {
    dense: foodJiagelaoDense,
    sparse: foodJiagelaoSparse,
    glow: foodJiagelaoGlow
  },
  "food-tubestation": {
    dense: foodTubestationDense,
    sparse: foodTubestationSparse,
    glow: foodTubestationGlow
  },
  "food-xiangshanting": {
    dense: foodXiangshantingDense,
    sparse: foodXiangshantingSparse,
    glow: foodXiangshantingGlow
  },
  "food-xintang": {
    dense: foodXintangDense,
    sparse: foodXintangSparse,
    glow: foodXintangGlow
  },
  "food-yunhaiyao": {
    dense: foodYunhaiyaoDense,
    sparse: foodYunhaiyaoSparse,
    glow: foodYunhaiyaoGlow
  },
  "food-samgyetang": {
    dense: foodSamgyetangDense,
    sparse: foodSamgyetangSparse,
    glow: foodSamgyetangGlow
  },
  "food-xibei": {
    dense: foodXibeiDense,
    sparse: foodXibeiSparse,
    glow: foodXibeiGlow
  }
} satisfies Partial<Record<StoreId, StoreArtLayers>>;

const warned = new Set<string>();

export function getStoreArtLayers(storeId: string): StoreArtLayers | null {
  const layers = availableStoreArt[storeId as keyof typeof availableStoreArt];
  if (!layers && __DEV__ && !warned.has(storeId)) {
    warned.add(storeId);
    console.warn(`[store-art] Missing dedicated ASCII art for ${storeId}; using placeholder.`);
  }
  return layers ?? null;
}
