import { StyleSheet } from "react-native";
import { mono, palette, pixelLatin } from "./theme";

export const styles = StyleSheet.create({
  app: { flex: 1, backgroundColor: palette.ink },
  scroll: { minHeight: "100%", alignItems: "center", paddingBottom: 20 },
  rail: { width: "100%", gap: 16 },
  vignette: { ...StyleSheet.absoluteFill, zIndex: 3, borderWidth: 16, borderColor: "rgba(0,0,0,0.22)", pointerEvents: "none" },
  texture: { ...StyleSheet.absoluteFill, zIndex: 2, opacity: 0.18, borderWidth: 1, borderColor: "rgba(216,180,106,0.12)", pointerEvents: "none" },
  header: { minHeight: 58, flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderBottomColor: palette.line, gap: 10 },
  iconButton: { width: 42, height: 42, alignItems: "center", justifyContent: "center" },
  iconText: { color: palette.gold, fontSize: 18, fontFamily: pixelLatin },
  iconMark: { color: palette.goldDim, fontSize: 11, fontFamily: pixelLatin, letterSpacing: 1 },
  systemTitle: { flex: 1, color: palette.gold, textAlign: "center", fontFamily: pixelLatin, fontSize: 13, letterSpacing: 3 },
  hero: { paddingTop: 6 },
  heroKickerRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 6 },
  heroKicker: { color: palette.goldDim, fontFamily: pixelLatin, fontSize: 11, letterSpacing: 4 },
  heroCount: { color: palette.goldDim, fontFamily: pixelLatin, fontSize: 11, letterSpacing: 2 },
  heroTitle: { color: palette.paper, fontFamily: mono, fontSize: 40, lineHeight: 50, fontWeight: "800", letterSpacing: 6, textShadowColor: "rgba(216,180,106,0.45)", textShadowRadius: 6 },
  heroArtBox: { width: "100%", maxWidth: 320, aspectRatio: 1, marginTop: 2, alignSelf: "center" },
  drawButton: { minHeight: 68, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 18, borderWidth: 1, borderColor: palette.coral, backgroundColor: palette.coral, paddingHorizontal: 22 },
  drawBracket: { color: "rgba(241,234,213,0.72)", fontSize: 24, fontFamily: pixelLatin },
  drawLabel: { color: palette.paper, fontFamily: mono, fontSize: 24, fontWeight: "800", letterSpacing: 10 },
  pressed: { opacity: 0.78, transform: [{ scale: 0.985 }] },
  disabled: { opacity: 0.55 },
  modeList: { flexDirection: "row", gap: 8 },
  modeRow: { flex: 1, minWidth: 0, minHeight: 156, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: palette.faint, backgroundColor: palette.inkSoft, paddingHorizontal: 8, paddingVertical: 10 },
  modeArt: { width: 78, height: 78, flexShrink: 0, marginBottom: -2 },
  modeTitleRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5 },
  modeMark: { fontFamily: mono, fontSize: 14, letterSpacing: 1 },
  modeLabel: { fontFamily: mono, fontSize: 17, fontWeight: "800", letterSpacing: 3 },
  modeSub: { marginTop: 5, color: palette.goldDim, fontFamily: pixelLatin, fontSize: 9, letterSpacing: 3 },
  modeMeta: { marginTop: 4, color: palette.muted, fontFamily: mono, fontSize: 10, letterSpacing: 1 },
  leader: { flex: 1, height: 1, backgroundColor: palette.faint, marginHorizontal: 2 },
  recentBlock: { marginTop: 4 },
  recentEmpty: { minHeight: 54, alignItems: "center", justifyContent: "center", borderBottomWidth: 1, borderBottomColor: palette.faint },
  recentEmptyText: { color: palette.muted, fontFamily: mono, fontSize: 12, letterSpacing: 2 },
  sectionHeading: { minHeight: 38, flexDirection: "row", alignItems: "center", gap: 8 },
  sectionPrefix: { color: palette.coral, fontFamily: pixelLatin, fontSize: 13 },
  sectionTitle: { color: palette.paper, fontFamily: mono, fontSize: 15, fontWeight: "800", letterSpacing: 3 },
  sectionAction: { color: palette.goldDim, fontFamily: mono, fontSize: 11, letterSpacing: 1 },
  storeRow: { minHeight: 54, flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderBottomColor: palette.faint, gap: 12 },
  storeGlyph: { width: 26, fontFamily: pixelLatin, fontSize: 13 },
  storeRowName: { color: palette.paper, fontFamily: mono, fontSize: 15, fontWeight: "700", flexShrink: 1 },
  storeRowMeta: { color: palette.goldDim, fontFamily: mono, fontSize: 11 },
  bottomNav: { minHeight: 64, flexDirection: "row", alignItems: "center", borderTopWidth: 1, borderTopColor: palette.line, marginTop: 2 },
  navItem: { flex: 1, alignItems: "center", justifyContent: "center" },
  navDivider: { color: palette.faint, fontFamily: mono, fontSize: 14 },
  navLabel: { color: palette.goldDim, fontFamily: mono, fontSize: 14, letterSpacing: 3 },
  navActive: { color: palette.coral },
  drawHeading: { paddingVertical: 10 },
  drawKicker: { color: palette.goldDim, fontFamily: pixelLatin, fontSize: 11, letterSpacing: 4 },
  drawPageTitle: { marginTop: 6, color: palette.paper, fontFamily: mono, fontSize: 30, fontWeight: "800", letterSpacing: 3 },
  resultPanel: { minHeight: 420, justifyContent: "center", alignItems: "center", borderWidth: 1, borderColor: palette.line, backgroundColor: palette.panel, padding: 20, overflow: "hidden" },
  outputLabel: { color: palette.goldDim, fontFamily: pixelLatin, fontSize: 11, letterSpacing: 4 },
  resultName: { marginTop: 12, color: palette.paper, fontFamily: mono, fontSize: 30, lineHeight: 40, fontWeight: "800", letterSpacing: 2, textAlign: "center", textShadowColor: "rgba(216,180,106,0.32)", textShadowRadius: 5 },
  resultMeta: { marginTop: 6, color: palette.gold, fontFamily: mono, fontSize: 12, letterSpacing: 1 },
  animatedArt: { width: "100%", maxWidth: 360, aspectRatio: 1, marginVertical: 2, position: "relative" },
  artLayer: { ...StyleSheet.absoluteFill, width: "100%", height: "100%", pointerEvents: "none" },
  artBand: { position: "absolute", left: 0, right: 0, overflow: "hidden" },
  artVignette: { ...StyleSheet.absoluteFill, borderWidth: 16, borderColor: "rgba(2,2,4,0.34)", shadowColor: "#000", shadowOpacity: 0.55, shadowRadius: 26, shadowOffset: { width: 0, height: 0 } },
  standbyLabel: { color: palette.goldDim, fontFamily: pixelLatin, fontSize: 11, letterSpacing: 6, marginBottom: 18 },
  standbyVisual: { width: "80%", maxWidth: 280, aspectRatio: 1 },
  emptyLogVisual: { width: "76%", maxWidth: 270, aspectRatio: 1 },
  waiting: { marginTop: 20, color: palette.muted, fontFamily: mono, fontSize: 15, letterSpacing: 3 },
  rendering: { marginTop: 20, color: palette.gold, fontFamily: mono, fontSize: 15, letterSpacing: 2 },
  tags: { flexDirection: "row", flexWrap: "wrap", justifyContent: "center", gap: 7 },
  tag: { color: palette.jade, borderWidth: 1, borderColor: "rgba(131,169,78,0.4)", fontFamily: mono, fontSize: 11, letterSpacing: 1, paddingHorizontal: 9, paddingVertical: 5 },
  note: { marginTop: 15, color: palette.muted, fontFamily: mono, fontSize: 13, lineHeight: 21, textAlign: "center" },
  actionRow: { flexDirection: "row", gap: 10 },
  secondaryAction: { flex: 1, minHeight: 56, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: palette.line },
  secondaryActionText: { color: palette.gold, fontFamily: mono, fontSize: 15, letterSpacing: 2 },
  primaryAction: { flex: 1.4, minHeight: 56, alignItems: "center", justifyContent: "center", backgroundColor: palette.coral, borderWidth: 1, borderColor: palette.coral },
  primaryActionText: { color: palette.paper, fontFamily: mono, fontSize: 15, fontWeight: "800", letterSpacing: 2 },
  historyList: { borderTopWidth: 1, borderTopColor: palette.line },
  historyRow: { minHeight: 68, flexDirection: "row", alignItems: "center", gap: 14, borderBottomWidth: 1, borderBottomColor: palette.faint },
  historyIndex: { width: 30, fontFamily: pixelLatin, fontSize: 13 },
  historyCopy: { flex: 1 },
  historyName: { color: palette.paper, fontFamily: mono, fontSize: 16, fontWeight: "700" },
  historyMeta: { marginTop: 5, color: palette.muted, fontFamily: mono, fontSize: 11, letterSpacing: 1 },
  clearButton: { minHeight: 48, alignItems: "center", justifyContent: "center", marginTop: 16, borderWidth: 1, borderColor: palette.coralDark },
  clearText: { color: palette.coral, fontFamily: mono, fontSize: 13, letterSpacing: 2 }
});
