// Regenerate store-art-assets.ts from stores.ts + files present in assets/store-art.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const mobileRoot = resolve(here, "..");
const storesSource = readFileSync(resolve(mobileRoot, "../packages/core/src/data/stores.ts"), "utf8");
const ids = [...storesSource.matchAll(/^\s+id:\s+"([^"]+)",/gm)].map((match) => match[1]);
const uniqueIds = [...new Set(ids)];
const variants = ["dense", "sparse", "glow"];
const assetRoot = join(mobileRoot, "assets", "store-art");

const complete = uniqueIds.filter((id) =>
  variants.every((variant) => existsSync(join(assetRoot, `${id}-${variant}.webp`)))
);

const camel = (id) => id.replace(/-(\w)/g, (_, c) => c.toUpperCase());

const imports = complete
  .flatMap((id) =>
    variants.map(
      (variant) =>
        `import ${camel(id)}${variant[0].toUpperCase()}${variant.slice(1)} from "../assets/store-art/${id}-${variant}.webp";`
    )
  )
  .join("\n");

const entries = complete
  .map(
    (id) =>
      `  "${id}": {\n    dense: ${camel(id)}Dense,\n    sparse: ${camel(id)}Sparse,\n    glow: ${camel(id)}Glow\n  }`
  )
  .join(",\n");

const file = `// AUTO-GENERATED by scripts/generate-art-map.mjs — do not edit by hand.
import type { ImageSourcePropType } from "react-native";
${imports}

export const storeIds = [
${uniqueIds.map((id) => `  "${id}"`).join(",\n")}
] as const;

export type StoreId = (typeof storeIds)[number];

export type StoreArtLayers = {
  dense: ImageSourcePropType;
  sparse: ImageSourcePropType;
  glow: ImageSourcePropType;
};

const availableStoreArt = {
${entries}
} satisfies Partial<Record<StoreId, StoreArtLayers>>;

const warned = new Set<string>();

export function getStoreArtLayers(storeId: string): StoreArtLayers | null {
  const layers = availableStoreArt[storeId as keyof typeof availableStoreArt];
  if (!layers && __DEV__ && !warned.has(storeId)) {
    warned.add(storeId);
    console.warn(\`[store-art] Missing dedicated ASCII art for \${storeId}; using placeholder.\`);
  }
  return layers ?? null;
}
`;

writeFileSync(join(mobileRoot, "src", "store-art-assets.ts"), file);
console.log(`Art map: ${complete.length}/${uniqueIds.length} stores with full layers.`);
